### ISSUE TITLE
uwpinject.exe -p 16512 -tid 8136 FindFirstFileW failed: error [00000002] ???????????

### ISSUE THREAD

**Issue by tiandan6666** [ddf8196/RTX2Deferred#2]
uwpinject.exe -p 16512 -tid 8136
FindFirstFileW failed: error [00000002] ???????????
![image](https://user-images.githubusercontent.com/56257382/216107214-213bcd02-263a-408d-b81d-749aaed53353.png)

**Comment by ddf8196** [comment]
检查RTX2Deferred.dll和BetterDeferred.dll是否在dlls文件夹中

**Comment by tiandan6666** [comment]
> 检查RTX2Deferred.dll和BetterDeferred.dll是否在dlls文件夹中
No error, but still can't run rtx

**Comment by ddf8196** [comment]
What is your GPU

**Comment by tiandan6666** [comment]
> 
GTX 1060 5G

**Comment by ddf8196** [comment]
GTX1060 supports ShaderModel 6.3, and is not the cause of this problem
Deferred rendering does not require DXR support
