### ISSUE TITLE
Many RTX features missing?

### ISSUE THREAD

**Issue by Plueres** [ddf8196/RTX2Deferred#3]
![image](https://user-images.githubusercontent.com/71077562/218863150-d7c15bc7-3347-48ad-9e70-da18024beaea.png)
My GPU supports direct3d 12 but it does not render most of the important shading features. In my example I used the neon district world from the marketplace. I also double checked if I had ray tracing on. Is there something I am missing?
![image](https://user-images.githubusercontent.com/71077562/218864579-b8577b19-952e-41d0-9600-4a8d9da87243.png)

**Comment by SIsilicon** [comment]
Most of the light in that world comes from blocks with emissive textures. Without raytracing those blocks can't do anything. A custom shader _could_ have that work, but that's outside of the scope of this project.

**Comment by Plueres** [comment]
And how about light rays from the sun? Would that work? Because I also cannot see the reflections from ice, underwater is kind of buggy and the clouds get blue at some point. I went here because of this post https://www.reddit.com/r/Minecraft/comments/112b2wj/shaders_running_on_a_gtx_1660ti_on_bedrock/ where they got it to run correctly

**Comment by SIsilicon** [comment]
This program is not enough to get that look. The shader used there is YSS special edition. You need to install that shader to get that look.

**Comment by Plueres** [comment]
THANK YOU! I'm gonna close the ticket now
