### ISSUE TITLE
hello everybody!

### ISSUE THREAD

**Issue by elecktro30060** [ddf8196/RTX2Deferred#4]
i have not found issues, But i have a request if it possible. i have x86 version by choice,,can you made support for this version 
 Microsoft.MinecraftUWP_1.19.6301.0_x86__8wekyb3d8bbwe, if you can not made a support 4 this version 1.19.63 can you add other version if is x86 version? or is just x64 version for full compatibility, im okay with that sorry for my bad english i speak french from QC usually thanks to read this :)

**Comment by ddf8196** [comment]
Only x64 versions are supported

**Comment by elecktro30060** [comment]
okay i understand that, and .. just ONE LAST things befor leavin' this "post" :)  thanks to U for ur answer!! FOR REAL !! and i love ur project, just don"T stop 2 update ,,  follow MC-VER :) if you want help, for your project, i can help TOO for FREE, and when i put  "materials.bin" of YSS shader  into the windowsapp folder for MC., i realizze  ( renderchunk and sky ) made my world crash, when activated yss shader  (( it is normale or just my gtx 1050ti is not powerfull to support  them )) i dont know LOL
